const DEFAULT_DURATION_SECONDS = parseInt(process.env.BATTLE_DURATION_SECONDS || '900', 10);
const TICK_SECONDS = parseInt(process.env.BATTLE_TICK_SECONDS || '5', 10);
const DARKNESS_DAMAGE_BASE = parseInt(process.env.DARKNESS_DAMAGE_BASE || '5', 10);
const DARKNESS_DAMAGE_NO_ATTENDANCE = parseInt(process.env.DARKNESS_DAMAGE_NO_ATTENDANCE || '20', 10);
const LIGHT_DAMAGE_PER_PLAYER = parseInt(process.env.LIGHT_DAMAGE_PER_PLAYER || '3', 10);

const DARKNESS_DAMAGE_PER_TARGET_USER = parseInt(process.env.DARKNESS_DAMAGE_PER_TARGET_USER || '500', 10);
const GUARDIAN_DAMAGE_BEFORE_FIRST_JOIN = parseInt(process.env.GUARDIAN_DAMAGE_BEFORE_FIRST_JOIN || '500', 10);
const GUARDIAN_DAMAGE_AFTER_FIRST_JOIN = parseInt(process.env.GUARDIAN_DAMAGE_AFTER_FIRST_JOIN || '250', 10);

const BATTLE_BASE_DURATION_SECONDS = 60 * 60;
const BATTLE_MIN_DURATION_SECONDS = 15 * 60;
const BATTLE_NO_ENTRY_DURATION_SECONDS = 3 * 60 * 60;
const BATTLE_SHRINK_PER_NEW_PLAYER_SECONDS = 0.0054;
const BATTLE_SYNC_SLOT_COUNT = Math.max(1, parseInt(process.env.BATTLE_SYNC_SLOT_COUNT || '60', 10) || 60);
const BATTLE_SYNC_INTERVAL_SECONDS = Math.max(1, parseInt(process.env.BATTLE_SYNC_INTERVAL_SECONDS || '60', 10) || 60);
const BATTLE_FINAL_REPORT_ACCEPT_SECONDS = Math.max(1, parseInt(process.env.BATTLE_FINAL_REPORT_ACCEPT_SECONDS || '30', 10) || 30);
const BATTLE_FINAL_WINDOW_SECONDS = BATTLE_FINAL_REPORT_ACCEPT_SECONDS;
const BATTLE_FINAL_REPORT_RETRY_INTERVAL_MS = Math.max(250, parseInt(process.env.BATTLE_FINAL_REPORT_RETRY_INTERVAL_MS || '2000', 10) || 2000);
const BATTLE_FINAL_REPORT_WINDOW_CAPACITY = Math.max(1, parseInt(process.env.BATTLE_FINAL_REPORT_WINDOW_CAPACITY || '500', 10) || 500);
const BATTLE_FINAL_MIN_DAMAGE_PCT = Math.max(0, Math.min(1, Number(process.env.BATTLE_FINAL_MIN_DAMAGE_PCT || '0.1')));
const BATTLE_FINAL_DEFER_MIN_MS = Math.max(0, Number(process.env.BATTLE_FINAL_DEFER_MIN_MS || (2 * 60 * 1000)));
const BATTLE_FINAL_DEFER_MAX_MS = Math.max(BATTLE_FINAL_DEFER_MIN_MS, Number(process.env.BATTLE_FINAL_DEFER_MAX_MS || (5 * 60 * 1000)));
const BATTLE_FINAL_SIDE_EFFECT_BATCH_SIZE = Math.max(
  1,
  Math.min(500, Number(process.env.BATTLE_FINAL_SIDE_EFFECT_BATCH_SIZE) || 25),
);
const BATTLE_FINISHED_ATTENDANCE_INLINE_LIMIT = Math.max(
  0,
  Math.floor(Number(process.env.BATTLE_FINISHED_ATTENDANCE_INLINE_LIMIT) || 1000),
);

const BATTLE_POLICY = Object.freeze({
  timerMode: 'dynamic_attendance',
  noParticipantsDurationSeconds: BATTLE_NO_ENTRY_DURATION_SECONDS,
  firstJoinDurationSeconds: BATTLE_BASE_DURATION_SECONDS,
  minDurationSeconds: BATTLE_MIN_DURATION_SECONDS,
  shrinkPerNewPlayerSeconds: BATTLE_SHRINK_PER_NEW_PLAYER_SECONDS,
  sync: Object.freeze({
    slotCount: BATTLE_SYNC_SLOT_COUNT,
    intervalSeconds: BATTLE_SYNC_INTERVAL_SECONDS,
  }),
});

function getBattlePolicy() {
  return {
    ...BATTLE_POLICY,
  };
}

function getBattleSyncConfig() {
  return {
    slotCount: BATTLE_SYNC_SLOT_COUNT,
    intervalSeconds: BATTLE_SYNC_INTERVAL_SECONDS,
  };
}

function getBattleFinalWindowConfig() {
  return {
    windowSeconds: BATTLE_FINAL_WINDOW_SECONDS,
    reportAcceptSeconds: BATTLE_FINAL_REPORT_ACCEPT_SECONDS,
    reportRetryIntervalMs: BATTLE_FINAL_REPORT_RETRY_INTERVAL_MS,
    reportWindowCapacity: BATTLE_FINAL_REPORT_WINDOW_CAPACITY,
    slotCount: BATTLE_SYNC_SLOT_COUNT,
    slotWindowMs: Math.floor((BATTLE_FINAL_REPORT_ACCEPT_SECONDS * 1000) / BATTLE_SYNC_SLOT_COUNT),
    minDamagePct: BATTLE_FINAL_MIN_DAMAGE_PCT,
  };
}

module.exports = {
  DEFAULT_DURATION_SECONDS,
  TICK_SECONDS,
  DARKNESS_DAMAGE_BASE,
  DARKNESS_DAMAGE_NO_ATTENDANCE,
  LIGHT_DAMAGE_PER_PLAYER,
  DARKNESS_DAMAGE_PER_TARGET_USER,
  GUARDIAN_DAMAGE_BEFORE_FIRST_JOIN,
  GUARDIAN_DAMAGE_AFTER_FIRST_JOIN,
  BATTLE_BASE_DURATION_SECONDS,
  BATTLE_MIN_DURATION_SECONDS,
  BATTLE_NO_ENTRY_DURATION_SECONDS,
  BATTLE_SHRINK_PER_NEW_PLAYER_SECONDS,
  BATTLE_SYNC_SLOT_COUNT,
  BATTLE_SYNC_INTERVAL_SECONDS,
  BATTLE_FINAL_REPORT_ACCEPT_SECONDS,
  BATTLE_FINAL_WINDOW_SECONDS,
  BATTLE_FINAL_REPORT_RETRY_INTERVAL_MS,
  BATTLE_FINAL_REPORT_WINDOW_CAPACITY,
  BATTLE_FINAL_MIN_DAMAGE_PCT,
  BATTLE_FINAL_DEFER_MIN_MS,
  BATTLE_FINAL_DEFER_MAX_MS,
  BATTLE_FINAL_SIDE_EFFECT_BATCH_SIZE,
  BATTLE_FINISHED_ATTENDANCE_INLINE_LIMIT,
  getBattlePolicy,
  getBattleSyncConfig,
  getBattleFinalWindowConfig,
};
