const {
  applyRiskCasePenalty,
  banRiskCaseGroup,
  deleteRiskCase,
  getRiskCase,
  listRiskCases,
  recomputeRisk,
  removeRelatedUserFromRiskCase,
  resolveRiskCase,
  sendRiskCaseContactEmail,
  sendRiskGroupContactEmail,
  unfreezeRiskCaseGroup,
  watchRiskCaseGroup,
} = require('./adminCms/riskCases');
const {
  clearCache,
  createBackup,
  getBackups,
  restoreBackup,
} = require('./adminCms/backups');
const {
  drawLotteryNowCms,
  exportFortuneWins,
  fortuneStatsCms,
  getFortuneConfigCms,
  listFortuneWins,
  patchFortuneLottery,
  patchFortuneRoulette,
} = require('./adminCms/fortune');
const {
  analyticsExport,
  analyticsOverview,
  analyticsTopPages,
  analyticsTrafficSources,
} = require('./adminCms/analytics');
const { listSystemErrors } = require('./adminCms/systemErrors');
const {
  campaignDeliveries,
  createMailCampaign,
  listMailCampaigns,
  runMailCampaign,
} = require('./adminCms/mailCampaigns');
const {
  createEmailTemplate,
  emailTemplateVersions,
  importEmailTemplateDefaults,
  listEmailTemplates,
  patchEmailTemplate,
  publishEmailTemplate,
  rollbackEmailTemplate,
} = require('./adminCms/emailTemplates');
const {
  articleVersions,
  contentSearch,
  createArticle,
  createPage,
  listArticles,
  listPages,
  pageVersions,
  patchArticle,
  patchPage,
  publishArticle,
  publishPage,
  rollbackArticle,
  rollbackPage,
} = require('./adminCms/content');
const {
  createModerationRule,
  deleteModerationRule,
  listModerationHits,
  listModerationRules,
  patchModerationRule,
  resolveModerationHit,
} = require('./adminCms/moderation');
const {
  blockIpRule,
  getAuthEvents,
  getIpRules,
  getUserSessions,
  revokeAllSessions,
  revokeUserSession,
  unblockIpRule,
} = require('./adminCms/securitySessions');

module.exports = {
  listRiskCases,
  getRiskCase,
  applyRiskCasePenalty,
  resolveRiskCase,
  unfreezeRiskCaseGroup,
  watchRiskCaseGroup,
  banRiskCaseGroup,
  deleteRiskCase,
  recomputeRisk,
  sendRiskCaseContactEmail,
  sendRiskGroupContactEmail,
  getIpRules,
  blockIpRule,
  unblockIpRule,
  getAuthEvents,
  getUserSessions,
  revokeUserSession,
  revokeAllSessions,
  listModerationRules,
  createModerationRule,
  patchModerationRule,
  deleteModerationRule,
  listModerationHits,
  resolveModerationHit,
  listPages,
  createPage,
  patchPage,
  publishPage,
  pageVersions,
  rollbackPage,
  listArticles,
  createArticle,
  patchArticle,
  publishArticle,
  articleVersions,
  rollbackArticle,
  contentSearch,
  analyticsOverview,
  analyticsTopPages,
  analyticsTrafficSources,
  analyticsExport,
  getFortuneConfigCms,
  patchFortuneRoulette,
  patchFortuneLottery,
  fortuneStatsCms,
  listFortuneWins,
  exportFortuneWins,
  drawLotteryNowCms,
  getBackups,
  createBackup,
  restoreBackup,
  clearCache,
  listSystemErrors,
  listMailCampaigns,
  createMailCampaign,
  runMailCampaign,
  campaignDeliveries,
  listEmailTemplates,
  createEmailTemplate,
  importEmailTemplateDefaults,
  patchEmailTemplate,
  publishEmailTemplate,
  emailTemplateVersions,
  rollbackEmailTemplate,
  removeRelatedUserFromRiskCase,
};
