import type { SiteLanguage } from '@/i18n/siteLanguage';

export const LANGUAGE_OPTIONS = [
  { value: 'af', label: 'Африкаанс' },
  { value: 'sq', label: 'Албанский' },
  { value: 'am', label: 'Амхарский' },
  { value: 'ar', label: 'Арабский' },
  { value: 'hy', label: 'Армянский' },
  { value: 'az', label: 'Азербайджанский' },
  { value: 'eu', label: 'Баскский' },
  { value: 'be', label: 'Белорусский' },
  { value: 'bn', label: 'Бенгальский' },
  { value: 'bs', label: 'Боснийский' },
  { value: 'bg', label: 'Болгарский' },
  { value: 'my', label: 'Бирманский' },
  { value: 'ca', label: 'Каталанский' },
  { value: 'ceb', label: 'Себуанский' },
  { value: 'zh-Hans', label: 'Китайский (упрощенный)' },
  { value: 'zh-Hant', label: 'Китайский (традиционный)' },
  { value: 'co', label: 'Корсиканский' },
  { value: 'hr', label: 'Хорватский' },
  { value: 'cs', label: 'Чешский' },
  { value: 'da', label: 'Датский' },
  { value: 'nl', label: 'Нидерландский' },
  { value: 'en', label: 'Английский' },
  { value: 'eo', label: 'Эсперанто' },
  { value: 'et', label: 'Эстонский' },
  { value: 'fi', label: 'Финский' },
  { value: 'fr', label: 'Французский' },
  { value: 'fy', label: 'Фризский' },
  { value: 'gl', label: 'Галисийский' },
  { value: 'ka', label: 'Грузинский' },
  { value: 'de', label: 'Немецкий' },
  { value: 'el', label: 'Греческий' },
  { value: 'gu', label: 'Гуджарати' },
  { value: 'ht', label: 'Гаитянский креольский' },
  { value: 'ha', label: 'Хауса' },
  { value: 'haw', label: 'Гавайский' },
  { value: 'he', label: 'Иврит' },
  { value: 'hi', label: 'Хинди' },
  { value: 'hmn', label: 'Хмонг' },
  { value: 'hu', label: 'Венгерский' },
  { value: 'is', label: 'Исландский' },
  { value: 'ig', label: 'Игбо' },
  { value: 'id', label: 'Индонезийский' },
  { value: 'ga', label: 'Ирландский' },
  { value: 'it', label: 'Итальянский' },
  { value: 'ja', label: 'Японский' },
  { value: 'jv', label: 'Яванский' },
  { value: 'kn', label: 'Каннада' },
  { value: 'kk', label: 'Казахский' },
  { value: 'km', label: 'Кхмерский' },
  { value: 'rw', label: 'Киньяруанда' },
  { value: 'ko', label: 'Корейский' },
  { value: 'ku', label: 'Курдский' },
  { value: 'ky', label: 'Киргизский' },
  { value: 'lo', label: 'Лаосский' },
  { value: 'la', label: 'Латинский' },
  { value: 'lv', label: 'Латышский' },
  { value: 'lt', label: 'Литовский' },
  { value: 'lb', label: 'Люксембургский' },
  { value: 'mk', label: 'Македонский' },
  { value: 'mg', label: 'Малагасийский' },
  { value: 'ms', label: 'Малайский' },
  { value: 'ml', label: 'Малаялам' },
  { value: 'mt', label: 'Мальтийский' },
  { value: 'mi', label: 'Маори' },
  { value: 'mr', label: 'Маратхи' },
  { value: 'mn', label: 'Монгольский' },
  { value: 'ne', label: 'Непальский' },
  { value: 'no', label: 'Норвежский' },
  { value: 'or', label: 'Ория' },
  { value: 'om', label: 'Оромо' },
  { value: 'ps', label: 'Пушту' },
  { value: 'fa', label: 'Персидский' },
  { value: 'pl', label: 'Польский' },
  { value: 'pt', label: 'Португальский' },
  { value: 'pa', label: 'Панджаби' },
  { value: 'ro', label: 'Румынский' },
  { value: 'ru', label: 'Русский' },
  { value: 'sm', label: 'Самоанский' },
  { value: 'sa', label: 'Санскрит' },
  { value: 'gd', label: 'Шотландский гэльский' },
  { value: 'sr', label: 'Сербский' },
  { value: 'st', label: 'Сесото' },
  { value: 'sn', label: 'Шона' },
  { value: 'sd', label: 'Синдхи' },
  { value: 'si', label: 'Сингальский' },
  { value: 'sk', label: 'Словацкий' },
  { value: 'sl', label: 'Словенский' },
  { value: 'so', label: 'Сомалийский' },
  { value: 'es', label: 'Испанский' },
  { value: 'su', label: 'Сунданский' },
  { value: 'sw', label: 'Суахили' },
  { value: 'sv', label: 'Шведский' },
  { value: 'tl', label: 'Тагальский' },
  { value: 'tg', label: 'Таджикский' },
  { value: 'ta', label: 'Тамильский' },
  { value: 'tt', label: 'Татарский' },
  { value: 'te', label: 'Телугу' },
  { value: 'th', label: 'Тайский' },
  { value: 'bo', label: 'Тибетский' },
  { value: 'ti', label: 'Тигринья' },
  { value: 'tr', label: 'Турецкий' },
  { value: 'tk', label: 'Туркменский' },
  { value: 'uk', label: 'Украинский' },
  { value: 'ur', label: 'Урду' },
  { value: 'ug', label: 'Уйгурский' },
  { value: 'uz', label: 'Узбекский' },
  { value: 'vi', label: 'Вьетнамский' },
  { value: 'cy', label: 'Валлийский' },
  { value: 'xh', label: 'Коса' },
  { value: 'yi', label: 'Идиш' },
  { value: 'yo', label: 'Йоруба' },
  { value: 'zu', label: 'Зулу' },
] as const;

const LANGUAGE_CODE_FOR_DISPLAY: Record<string, string> = {
  'zh-Hans': 'zh-CN',
  'zh-Hant': 'zh-TW',
};

const LANGUAGE_LABELS_EN: Record<string, string> = {
  'zh-Hans': 'Chinese (Simplified)',
  'zh-Hant': 'Chinese (Traditional)',
  ceb: 'Cebuano',
  fy: 'Frisian',
  haw: 'Hawaiian',
  hmn: 'Hmong',
  jv: 'Javanese',
  rw: 'Kinyarwanda',
  my: 'Burmese',
  or: 'Odia',
  om: 'Oromo',
  ps: 'Pashto',
  sa: 'Sanskrit',
  sd: 'Sindhi',
  sm: 'Samoan',
  st: 'Sesotho',
  su: 'Sundanese',
  tl: 'Tagalog',
  ti: 'Tigrinya',
  ug: 'Uyghur',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  zu: 'Zulu',
};

export function getLanguageOptionLabel(
  option: (typeof LANGUAGE_OPTIONS)[number],
  siteLanguage: SiteLanguage,
) {
  if (siteLanguage !== 'en') {
    return option.label;
  }

  const code = LANGUAGE_CODE_FOR_DISPLAY[option.value] || option.value;

  try {
    const display = new Intl.DisplayNames(['en'], { type: 'language' });
    const fromIntl = display.of(code);
    if (fromIntl) {
      return fromIntl.charAt(0).toUpperCase() + fromIntl.slice(1);
    }
  } catch {
  }

  return LANGUAGE_LABELS_EN[option.value] || option.label;
}
